#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	l="ls -la" \
	la="ls -a" \
	ll="ls -l"
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query"

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	weath="less -S ~/.local/share/weatherreport" \


alias yay='yay --answerdiff N'
alias bc='bc ql'
alias vim='nvim' \
	vi='nvim' \
	v='nvim'


alias h='htop'

alias v.aliases="$EDITOR ~/.dotfiles/configs/zsh/aliasrc"
alias v.sway="$EDITOR ~/.dotfiles/configs/sway/config"
alias v.kitty="$EDITOR ~/.dotfiles/configs/kitty/kitty.conf"
alias v.mpv="$EDITOR ~/.dotfiles/configs/mpv/linux-mpv.conf"
alias v.nvim="$EDITOR ~/.dotfiles/configs/nvim/init.vim"
alias v.waybar="$EDITOR ~/.dotfiles/configs/waybar/config"
alias v.zsh="$EDITOR ~/.dotfiles/configs/zsh/.zshrc"
alias v.zshenv="$EDITOR ~/.dotfiles/configs/.zshenv"
alias v.zprofile="$EDITOR ~/.dotfiles/configs/zsh/.zprofile"
alias v.ranger="$EDITOR ~/.dotfiles/configs/zsh/rc.conf"

# Managing dotfiles / otherwise that is a lot of typting for routine file managment
alias	dotf="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME" \
		dota="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME add" \
		dots="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME status -uno" \
		dotc="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME commit" \
		dotm="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME commit -m" \
		dotb="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME branch" \
		dotch="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME checkout" \
		dotl="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME log --oneline" \
		dotd="/usr/bin/git --git-dir=$HOME/Code/dotfiles --work-tree=$HOME diff"
